# Generated by Django 4.0.4 on 2022-07-20 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_habitantes', models.IntegerField()),
                ('estrato_se', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=75)),
                ('seleccion', models.CharField(max_length=200)),
                ('unidad', models.CharField(max_length=20)),
                ('respuesta_consumo', models.FloatField()),
                ('fecha_pub', models.DateTimeField(verbose_name='fecha publicada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co2_app.usuario')),
            ],
        ),
    ]
