# Generated by Django 4.0.4 on 2022-07-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='seleccion',
            field=models.IntegerField(),
        ),
    ]
